### ISSUE TITLE
자판기 HTML

### ISSUE THREAD

**Issue by choichoigang** [codesquad-memeber-2020/vm-1#2]
- [x] html 구조 설계

- [x] machine section (상품 , 선택) 과 wallet section (user) 을 나눠서 구조화

- [x] 서버의 데이터를 기반으로 작성될 부분 지정

**Comment by choichoigang** [comment]
![Screenshot 2020-03-10 at 15 43 24](https://user-images.githubusercontent.com/49897409/76286599-f6733680-62e5-11ea-9e86-44e493defa42.jpg)
issue 기반으로 작업한 html View

**Comment by crongro** [comment]
디테일한 버튼UI잘 봤습니다.
